# Generated by Django 4.0.2 on 2022-02-12 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninja',
            old_name='city',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='ninja',
            old_name='name',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='ninja',
            name='state',
        ),
    ]
